Fix a checksum exception about bazel-zig-cc
proxy-wasm/proxy-wasm-cpp-host pull request #335
Opened 2023-03-27 01:47 UTC by lum1n0us

```
WARNING: Download from https://git.sr.ht/~motiejus/bazel-zig-cc/archive/v0.4.4.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was b3dd78971f0f831f62d84ae96656bdb0941b91b7c80097d69f5be213351cc6ff but wanted ad6384b4d16ebb3e5047df6548a195e598346da84e5f320250beb9198705ac81
```

2023-03-27 08:28 UTC, mathetake approved these changes
LGTM - Verified this is correct https://github.com/proxy-wasm/proxy-wasm-cpp-host/actions/runs/4529975569/jobs/7978375729?pr=337

2023-03-27 08:30 UTC, mathetake requested changes

2023-03-27 08:30 UTC, mathetake commented on bazel/repositories.bzl
>          url = "https://git.sr.ht/~motiejus/bazel-zig-cc/archive/v0.4.4.tar.gz",
having said that, could you change this URL to https://github.com/uber/bazel-zig-cc per https://git.sr.ht/~motiejus/bazel-zig-cc ?

2023-03-28 06:33 UTC, PiotrSikora commented
Any chance to update it to latest version while you're at it? Assuming it's a simple version bump.

2023-03-28 06:34 UTC, lum1n0us commented
like [v1.0.1](https://github.com/uber/bazel-zig-cc/releases/tag/v1.0.1)?

2023-03-28 06:35 UTC, PiotrSikora commented
Yes.

2023-03-28 07:11 UTC, PiotrSikora commented
> Does it suggest that we should use `load("@bazel-zig-cc//toolchain:defs.bzl", zig_register_toolchains = "toolchains")` to replace `load("@bazel-zig-cc//toolchain:defs.bzl", zig_register_toolchains = "register_toolchains")` in _bazel/dependencies.bzl_ ?

Correct.

You could also follow the official example and use:
```
load("@bazel-zig-cc//toolchain:defs.bzl", zig_toolchains = "toolchains")
```
and replace `zig_register_toolchains` with `zig_toolchains` later in the rules.

2023-03-28 07:57 UTC, PiotrSikora commented
Could you fix DCO (`Signed-off-by` is missing in the last commit)?

2023-03-29 00:45 UTC, PiotrSikora approved these changes
Thanks!

2023-03-29 00:49 UTC, mathetake approved these changes

2023-03-29 00:50 UTC, merged