Fix v8 gcc Bazel build using -Wno-nonnull. Fixes #340.
proxy-wasm/proxy-wasm-cpp-host pull request #343
Opened 2023-04-26 16:25 UTC by martijneken

2023-04-26 17:03 UTC, martijneken commented on bazel/external/v8.patch
> -
Whoops yes, I added a commit. I'm new to Git so let me know if I didn't do it right.

2023-04-26 17:41 UTC, PiotrSikora commented
Looks good, but you need to fix the DCO bot (the `Signed-off-by` line must be present in all commits).

```
git commit --amend --signoff && git push --force ...
```

2023-04-26 18:11 UTC, martijneken commented
> Looks good, but you need to fix the DCO bot (the `Signed-off-by` line must be present in all commits).
Thanks, done.

> We need to fix the CI with hermetic_cc_toolchain before merging anything.
ACK. https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/345

2023-04-26 21:56 UTC, martijneken commented
Added CI for GCC and v8. Still blocked on https://github.com/proxy-wasm/proxy-wasm-cpp-host/pull/345

2023-04-27 16:39 UTC, PiotrSikora requested changes

2023-04-28 02:22 UTC, martijneken commented on .github/workflows/test.yml
> +          flags: --config=clang --config=gcc
Ugh sorry, good catch.

2023-04-28 19:40 UTC, PiotrSikora approved these changes
Thanks!

2023-04-28 19:42 UTC, merged